# Resolução de sistemas de equações lineares

## Importações

In [2]:
import numpy as np

## Definições

In [131]:
A1 = np.array([
          [0, 1, 3, 2, 4],
          [8, 2, 9, -1, 2],
          [5, 1, 1, 7, 2],
          [-2, 4, 5, 1, 0],
          [7, -3, 2, -4, 1]
          ], dtype='float')  

B1 = np.array([3, -5, 6, -1, 8], dtype='float')

A2 = np.array([
          [1, 2, 4],
          [3, 1, -1],
          [3, 2, 1]
          ], dtype='float')
          
B2 = np.array([1, 2, 5], dtype='float')

## Algoritmos

### Eliminação de Gauss s/ Pivotamento

In [98]:
def gauss_elimination(coeficients, constants):
  A = np.copy(coeficients)
  B = np.copy(constants)
  length = len(A) - 1

  if A[0, 0] == 0:
    print('Não é possível resolver o sistema, pivô nulo!')
    return None

  # superior matrix
  for base in range(length):
    for row in range(base + 1, len(A)):
      factor = A[row, base] / A[base, base]
      A[row, base] = 0

      for col in range(base + 1, len(A)):
        A[row, col] = A[row, col] - factor * A[base, col]

      B[row] = B[row] - (factor * B[base])

  # resolution
  x = np.zeros(len(A), dtype='float')
  x[length] = B[length] / A[length, length]

  for row in range(length, 0, -1):
    s = 0
    for col in range(row + 1, len(A)):
      s = s + A[row, col] * x[col]
      x[row] = (B[row] - s) / A[row, row]

  return A, B, x


### Eliminação de Gauss Com Pivotamento

In [127]:
def gauss_elimination_pivoting(coeficients, constants):
  A = np.copy(coeficients)
  B = np.copy(constants)
  length = len(A) - 1

  # superior matrix
  for base in range(length):
    # choose pivot
    max = (abs(A[base, base]), base)
    for row in range(base, length - 1):
      if abs(A[row + 1, 0]) > max[0]:
        max = (A[row + 1, 0], row + 1)

    if max[0] != base:
      aux = np.copy(A[base])
      A[base] = A[max[1]]
      A[max[1]] = aux

      aux = np.copy(B[base])
      B[base] = B[max[1]]
      B[max[1]] = aux

    for row in range(base + 1, len(A)):
      factor = A[row, base] / A[base, base]
      A[row, base] = 0

      for col in range(base + 1, len(A)):
        A[row, col] = A[row, col] - factor * A[base, col]

      B[row] = B[row] - (factor * B[base])

  # resolution
  x = np.zeros(len(A), dtype='float')
  x[length] = B[length] / A[length, length]

  for row in range(length, 0, -1):
    s = 0
    for col in range(row + 1, len(A)):
      s = s + A[row, col] * x[col]
      x[row] = (B[row] - s) / A[row, row]

  return A, B, x

## Exercícios

In [132]:
gauss_elimination_pivoting(A1, B1)

[[ 8.  2.  9. -1.  2.]
 [ 0.  1.  3.  2.  4.]
 [ 5.  1.  1.  7.  2.]
 [-2.  4.  5.  1.  0.]
 [ 7. -3.  2. -4.  1.]]
[[ 8.     2.     9.    -1.     2.   ]
 [ 0.     1.     3.     2.     4.   ]
 [ 0.    -0.25  -4.625  7.625  0.75 ]
 [ 0.     4.5    7.25   0.75   0.5  ]
 [ 0.    -4.75  -5.875 -3.125 -0.75 ]]
[[  8.      2.      9.     -1.      2.   ]
 [  0.      1.      3.      2.      4.   ]
 [  0.      0.     -3.875   8.125   1.75 ]
 [  0.      0.     -6.25   -8.25  -17.5  ]
 [  0.      0.      8.375   6.375  18.25 ]]
[[  8.           2.           9.          -1.           2.        ]
 [  0.           1.           3.           2.           4.        ]
 [  0.           0.          -3.875        8.125        1.75      ]
 [  0.           0.           0.         -21.35483871 -20.32258065]
 [  0.           0.           0.          23.93548387  22.03225806]]


(array([[  8.        ,   2.        ,   9.        ,  -1.        ,
           2.        ],
        [  0.        ,   1.        ,   3.        ,   2.        ,
           4.        ],
        [  0.        ,   0.        ,  -3.875     ,   8.125     ,
           1.75      ],
        [  0.        ,   0.        ,   0.        , -21.35483871,
         -20.32258065],
        [  0.        ,   0.        ,   0.        ,   0.        ,
          -0.74622356]]),
 array([ -5.        ,   3.        ,   9.875     , -31.67741935,
         12.46223565]),
 array([  0.        , -43.98380567,  26.34412955,  17.37651822,
        -16.70040486]))