# Resolução de sistemas de equações lineares

## Importações

In [2]:
import numpy as np

| 0 + x + 3x + 2x + 4x = 3 
| 8x - 2x + 9x -x + 2x = -5 
| 5x + x + x + 7x + 2x = 6
| -2x + 4x + 5x + x + 0 = -1
| 7x - 3x + 2x - 4x + x = 8

## Definições

In [91]:
matrix1 = np.array([
          [0, 1, 3, 2, 4, 3],
          [8, 2, 9, -1, 2, -5],
          [5, 1, 1, 7, 2, 6],
          [-2, 4, 5, 1, 0, -1],
          [7, -3, 2, -4, 1, 8]
          ], dtype='float')  

A2 = np.array([
          [1, 2, 4],
          [3, 1, -1],
          [3, 2, 1]
          ], dtype='float')
          
B2 = np.array([1, 2, 5], dtype='float')

#### Eliminação de Gauss s/ Pivotamento

In [95]:
def gauss_elimination(coeficients, constants):
  A = np.copy(coeficients)
  B = np.copy(constants)
  length = len(A) - 1

  if A[0, 0] == 0:
    print('Não é possível resolver o sistema, pivô nulo!')
    return None

  # superior matrix
  for base in range(length):
    for row in range(base + 1, len(A)):
      factor = A[row, base] / A[base, base]
      A[row, base] = 0

      for col in range(base + 1, len(A)):
        A[row, col] = A[row, col] - factor * A[base, col]

      B[row] = B[row] - (factor * B[base])

  # resolution
  x = np.zeros(len(A), dtype='float')
  x[length] = B[length] / A[length, length]

  for row in range(length, 0, -1):
    s = 0
    for col in range(row + 1, len(A)):
      s = s + A[row, col] * x[col]
      x[row] = (B[row] - s) / A[row, row]

  return A, B, x


In [96]:
gauss_elimination(A2, B2)

0
1


(array([[  1. ,   2. ,   4. ],
        [  0. ,  -5. , -13. ],
        [  0. ,   0. ,  -0.6]]),
 array([ 1. , -1. ,  2.8]),
 array([ 0.        , 12.33333333, -4.66666667]))

In [74]:
np.linalg.solve(A2, B2)

array([-5.        , 12.33333333, -4.66666667])